({
   dataTypes: [
     {name: "int", label: "int" }, {name: "string", label: "string" },
     {name: "password", label: "password" },{name: "date", label: "date" },
     {name: "time", label: "time"},{name: "datetime", label: "datetime"}
   ],
   conditionOperators:  [
     {id: "true", name: "true"},{id : "and", name: "and"}, {id: "or", name: "or" },
     {id: "not", name: "not"}, {id: "eq", name: "equals"},{id: "gt", name: "greater than"},
     {id: "lt", name: "less than"}, {id: "success", name: "isSuccess"}
   ],
   file: "File",
   "new": "New",
   open: "Open File",
   save: "Save Project and Download",
   download: "Download Ajml",
   generate: "Generate",
   war: "Application Archive File (.war)",
   projectExploer: "projectExploer",
   toolbox: "toolbox",
   loadFile: "Load File",
   load: "load",
   newApplication: "New Application",
   create: "create",
   property: "property",
   event: "event",
   log: "log",
   databases: "databases",
   appName : "application name",
   contextMenu : "context menu",
   dropFunction: "<br/>drop function",
//   dropCondition: "<br/>&nbsp;drop area(condition)",
   dropCondition: "<br/>drop condition",
   condition: "condition",
   conditionSelect: "condition: ",
   undefinedElem: "unconfigured",
   enter: "enter",
   databaseSelect: "database: ",
   initItems: "init items",
   initItem: "init item",
   add: "add",
   change: "change",
   select: "select",
   elementSelect: "element: ",
   methodSelect: "method: ",
   login: "login",
   param: "param",
   noElement: "no element",
   addEvent: "add event",
   databases: "databases",
   events: "events",
   interfaces: "UI",
   unset: "unset",
   noFunc : "no func",
   remove: "remove",
   reflesh: "reflesh"
})