({
   dataTypes: [
     {id: "int", name: "int" }, {id: "string", name: "string" },
     {id: "password", name: "password" },{id: "date", name: "date" },
     {id: "time", name: "time"},{id: "datetime", name: "datetime"}
   ],
   conditionOperators:  [
     {id: "true", name: "true"},{id : "and", name: "and"}, {id: "or", name: "or" },
     {id: "not", name: "not"}, {id: "eq", name: "equals"},{id: "gt", name: "greater than"},
     {id: "lt", name: "less than"}, {id: "success", name: "isSuccess"}
   ],
   file: "File",
   "new": "New",
   open: "Open File",
   save: "Save ProjectÅ@and Download",
   download: "Download Ajml",
   generate: "Generate",
   war: "Application Archive File (.war)",
   projectExploer: "projectExploer",
   toolbox: "toolbox",
   loadFile: "Load File",
   load: "load",
   newApplication: "New Application",
   create: "create",
   property: "property",
   event: "event",
   log: "log",
   databases: "databases",
   appName : "application name",
   contextMenu : "context menu",
   dropFunction: "drop area(event)",
   dropCondition: "<br/>&nbsp;drop area(condition)",
   condition: "condition",
   conditionSelect: "condition: ",
   undefinedElem: "unconfigured",
   enter: "enter",
   databaseName: "database name: ",
   initItems: "init items",
   initItem: "init item",
   add: "add",
   change: "change",
   select: "select",
   elementSelect: "element: ",
   methodSelect: "method: ",
   login: "login",
   param: "param",
   noElement: "no element",
   addEvent: "add event",
   databases: "databases",
   events: "events",
   interfaces: "UI"
})